# This compose file overrides the base one in the demo folder and is meant to be used in production
version: "3"

services:
  haystack-api:
    image: "deepset/haystack:gpu-v1.12.2"
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: 1
            capabilities: [gpu]
    restart: always
    environment:
      CONCURRENT_REQUEST_PER_WORKER: 16
      HAYSTACK_EXECUTION_CONTEXT: "public_demo"
      PIPELINE_YAML_PATH: /opt/venv/lib/python3.7/site-packages/rest_api/pipeline/pipelines_dpr.haystack-pipeline.yml

  elasticsearch:
    restart: always

  ui:
    restart: always
    environment:
      DEFAULT_DOCS_FROM_RETRIEVER: 7
      DEFAULT_NUMBER_OF_ANSWERS: 5
      DISABLE_FILE_UPLOAD: 1
